# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Use Python 3.10'

- script: |
    python -m pip install --upgrade pip
    pip install azure-ai-ml
    pip install azure-identity
    pip install mldesigner
    pip install pandas
    pip install numpy
    pip install scikit-learn
    pip install datetime
    pip install joblib
  displayName: 'Install AzureML dependencies'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ml-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=AZURE_CLIENT_ID;]$servicePrincipalId"
      echo "##vso[task.setvariable variable=AZURE_CLIENT_SECRET;]$servicePrincipalKey"
      echo "##vso[task.setvariable variable=AZURE_TENANT_ID;]$tenantId"
    addSpnToEnvironment: true

- script: |
    python src/create-and-run-pipeline.py
  displayName: 'Create and Execute Azure Pipeline'

