name: mlflow-env
channels:
  - defaults
dependencies:
  - python=3.11
  - pip=23.2.1
  - pip:
    - mlflow==2.8.1
    - azureml-mlflow==1.54.0
    - azureml-core==1.54.0
    - joblib==1.2.0
    - mldesigner==0.1.0b12
    - scikit-learn==1.3.0
    - pandas==2.0.3
    - numpy==1.24.3
    - cloudpickle==2.2.1
    - psutil==5.9.4
    - Flask==2.0.2
    - Werkzeug==2.2.2
    - azureml-inference-server-http